package metrics

/*
Copyright 2024 The external-dns-infoblox-webhook Contributors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

Generated by GoLic, for more details see: https://github.com/AbsaOSS/golic
*/

import (
	"github.com/prometheus/client_golang/prometheus"
)

var (
	FailedApiCallsTotal = prometheus.NewCounter(prometheus.CounterOpts{
		Name: "external_dns_webhook_failed_api_calls_total",
		Help: "Total number of failed API calls",
	})
	TotalApiCalls = prometheus.NewCounter(prometheus.CounterOpts{
		Name: "external_dns_webhook_total_api_calls",
		Help: "Total number of API calls",
	})

	ApiCallLatency = prometheus.NewSummaryVec(prometheus.SummaryOpts{
		Name: "external_dns_webhook_api_call_latency_seconds",
		Help: "Latency of Infoblox API calls",
	}, []string{"method"}) // method label to differentiate API calls
)

func init() {
	prometheus.MustRegister(FailedApiCallsTotal, ApiCallLatency, TotalApiCalls)
}
