---
name: GolangCI
on:
  push:
    paths-ignore:
      - '**.md'
  pull_request:
    branches:
      - main
    paths-ignore:
      - '**.md'
jobs:
  lint:
    name: GolangCI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: GolangCI
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.55.2
          args: --timeout=3m
