---
name: Test
on:
  push:
    paths-ignore:
      - '**.md'
  pull_request:
    branches:
      - main
    paths-ignore:
      - '**.md'
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Dependencies
        env:
          GOPROXY: https://proxy.golang.org,direct
        run: go mod download

      - name: Test
        run: make test
